"""Tests for config-sync CLI."""

import tempfile
from pathlib import Path

from config_sync.cli import main, read_source, strip_frontmatter, init_rules


def test_strip_frontmatter():
    input_text = "---\nname: test\n---\nContent here"
    result = strip_frontmatter(input_text)
    assert result == "Content here"
    assert "---" not in result


def test_strip_frontmatter_none():
    input_text = "No frontmatter here"
    result = strip_frontmatter(input_text)
    assert result == input_text


def test_read_source_from_rules():
    with tempfile.TemporaryDirectory() as tmp:
        rules = Path(tmp) / ".claude" / "rules"
        rules.mkdir(parents=True)
        (rules / "style.md").write_text("# Style\nUse 2 spaces")
        result = read_source(Path(tmp))
        assert "Use 2 spaces" in result


def test_read_source_fallback_claude_md():
    with tempfile.TemporaryDirectory() as tmp:
        (Path(tmp) / "CLAUDE.md").write_text("# Rules\nBe careful")
        result = read_source(Path(tmp))
        assert "Be careful" in result


def test_init_splits_claude_md():
    with tempfile.TemporaryDirectory() as tmp:
        claude_md = Path(tmp) / "CLAUDE.md"
        claude_md.write_text("## Style\nUse 2 spaces\n\n## Testing\nWrite tests first")
        init_rules(Path(tmp))
        rules_dir = Path(tmp) / ".claude" / "rules"
        assert rules_dir.exists()
        files = list(rules_dir.glob("*.md"))
        assert len(files) >= 2


def test_end_to_end_generates_files():
    """Integration test: generate configs from rules and verify output."""
    import sys

    with tempfile.TemporaryDirectory() as tmp:
        rules = Path(tmp) / ".claude" / "rules"
        rules.mkdir(parents=True)
        (rules / "style.md").write_text("## Style\n- Use 2 spaces\n- Prefer immutability")

        sys.argv = ["config-sync", tmp]
        main()

        assert (Path(tmp) / "AGENTS.md").exists()
        assert (Path(tmp) / "GEMINI.md").exists()
        assert (Path(tmp) / ".cursor" / "rules" / "config-sync.mdc").exists()
        assert (Path(tmp) / ".github" / "copilot-instructions.md").exists()
        assert (Path(tmp) / "CONVENTIONS.md").exists()
        assert (Path(tmp) / ".goosehints").exists()
        assert (Path(tmp) / ".rules").exists()

        agents = (Path(tmp) / "AGENTS.md").read_text()
        assert "Use 2 spaces" in agents
        assert "Generated by config-sync" in agents

        goose = (Path(tmp) / ".goosehints").read_text()
        assert "##" not in goose
        assert "Use 2 spaces" in goose
