"""Tests for config-sync generators."""

from config_sync.generators import (
    TOOLS,
    format_aider,
    format_codex,
    format_cursor,
    format_goose,
    format_generic,
)


SAMPLE_SOURCE = "## Code Style\n\n- Use 2 spaces\n- Prefer immutability\n\n## Testing\n\n- Write tests first"


def test_format_generic_adds_header():
    result = format_generic(SAMPLE_SOURCE, "Test Title")
    assert result.startswith("<!-- Generated by config-sync")
    assert "# Test Title" in result
    assert SAMPLE_SOURCE in result


def test_format_codex():
    result = format_codex(SAMPLE_SOURCE)
    assert "AGENTS" not in result  # no tool-specific markers
    assert "# Project Instructions" in result
    assert "Use 2 spaces" in result


def test_format_cursor_mdc():
    result = format_cursor(SAMPLE_SOURCE)
    assert result.startswith("---\n")
    assert "description:" in result
    assert "globs: **" in result
    assert "alwaysApply: true" in result
    assert "Use 2 spaces" in result


def test_format_aider_condensed():
    result = format_aider(SAMPLE_SOURCE)
    assert "<!-- Generated by config-sync" in result
    assert "# Conventions" in result
    # Should be condensed to bullets
    assert "- Use 2 spaces" in result or "- Prefer immutability" in result


def test_format_goose_no_markdown():
    result = format_goose(SAMPLE_SOURCE)
    assert "<!--" not in result  # no HTML comments
    assert "##" not in result  # no markdown headers
    assert "Use 2 spaces" in result  # plain text


def test_all_tools_have_formatter():
    """Every registered tool has a valid tuple (file, desc, formatter)."""
    for tool_id, (filename, desc, formatter) in TOOLS.items():
        assert filename, f"{tool_id} has no filename"
        assert desc, f"{tool_id} has no description"
        assert callable(formatter), f"{tool_id} formatter is not callable"
        # Formatter should produce non-empty output
        result = formatter(SAMPLE_SOURCE)
        assert len(result) > 0, f"{tool_id} formatter produced empty output"


def test_all_formatters_are_unique():
    """No two tools should produce identical output (except generic ones)."""
    outputs = {}
    for tool_id, (_, _, formatter) in TOOLS.items():
        result = formatter(SAMPLE_SOURCE)
        outputs[tool_id] = result
    # Codex and Gemini use same generic format — that's OK
    # But cursor, goose, aider should be different
    assert outputs["cursor"] != outputs["codex"]
    assert outputs["goose"] != outputs["codex"]
    assert outputs["aider"] != outputs["codex"]
