"""Config generators for each supported AI coding tool."""

import re

GENERATED_HEADER = "<!-- Generated by config-sync. Edit source at .claude/rules/ -->\n"


def format_generic(source: str, title: str) -> str:
    """Flat markdown — used by most tools."""
    return f"{GENERATED_HEADER}# {title}\n\n{source}\n"


def format_codex(source: str) -> str:
    """AGENTS.md — Codex CLI, Amp, OpenCode, Warp."""
    return format_generic(source, "Project Instructions")


def format_gemini(source: str) -> str:
    """GEMINI.md — Gemini CLI."""
    return format_generic(source, "Project Instructions")


def format_cursor(source: str) -> str:
    """MDC format with frontmatter — Cursor."""
    return f"---\ndescription: Project coding rules (auto-synced)\nglobs: **\nalwaysApply: true\n---\n\n{source}\n"


def format_copilot(source: str) -> str:
    """GitHub Copilot instructions."""
    return format_generic(source, "Copilot Instructions")


def format_windsurf(source: str) -> str:
    """Windsurf rules."""
    return format_generic(source, "Windsurf Rules")


def format_cline(source: str) -> str:
    """Cline / Roo Code rules."""
    return format_generic(source, "Cline Rules")


def format_aider(source: str) -> str:
    """Condensed bullet-point style — Aider."""
    lines = source.split("\n")
    condensed = []
    for line in lines:
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith("## "):
            condensed.append(f"\n# {stripped[3:]}")
        elif stripped.startswith("- ") or stripped.startswith("* "):
            condensed.append(stripped)
        elif stripped.startswith("#"):
            condensed.append(stripped)
        else:
            condensed.append(f"- {stripped}")
    return f"{GENERATED_HEADER}# Conventions\n{chr(10).join(condensed)}\n"


def format_kiro(source: str) -> str:
    """Kiro steering rules."""
    return format_generic(source, "Steering Rules")


def format_amazonq(source: str) -> str:
    """Amazon Q Developer rules."""
    return format_generic(source, "Amazon Q Rules")


def format_goose(source: str) -> str:
    """Line-per-rule, no markdown — Goose."""
    lines = source.split("\n")
    hints = []
    for line in lines:
        stripped = line.strip()
        if not stripped:
            continue
        stripped = re.sub(r"^#+\s*", "", stripped)
        stripped = re.sub(r"^[-*]\s+", "", stripped)
        if stripped:
            hints.append(stripped)
    return "\n".join(hints) + "\n"


def format_trae(source: str) -> str:
    """Trae AI rules."""
    return format_generic(source, "Trae Rules")


def format_zed(source: str) -> str:
    """Zed rules."""
    return format_generic(source, "Rules")


# Tool registry: id → (output_file, description, formatter)
TOOLS: dict[str, tuple[str, str, object]] = {
    "codex": ("AGENTS.md", "Codex CLI / Amp / OpenCode / Warp", format_codex),
    "gemini": ("GEMINI.md", "Gemini CLI", format_gemini),
    "cursor": (".cursor/rules/config-sync.mdc", "Cursor", format_cursor),
    "copilot": (".github/copilot-instructions.md", "GitHub Copilot", format_copilot),
    "windsurf": (".windsurf/rules/config-sync.md", "Windsurf", format_windsurf),
    "cline": (".clinerules/config-sync.md", "Cline / Roo Code", format_cline),
    "aider": ("CONVENTIONS.md", "Aider", format_aider),
    "kiro": (".kiro/steering/config-sync.md", "Kiro (AWS)", format_kiro),
    "amazonq": (".amazonq/rules/config-sync.md", "Amazon Q Developer", format_amazonq),
    "goose": (".goosehints", "Goose (Block)", format_goose),
    "trae": (".trae/rules/config-sync.md", "Trae AI (ByteDance)", format_trae),
    "zed": (".rules", "Zed", format_zed),
}
